// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX0qt1vX0t8aj3seceHxAlnKzkHmT4xB4',
    appId: '1:554206459812:web:01d7b4bfec12959028f331',
    messagingSenderId: '554206459812',
    projectId: 'king-of-sleeping',
    authDomain: 'king-of-sleeping.firebaseapp.com',
    storageBucket: 'king-of-sleeping.firebasestorage.app',
    measurementId: 'G-00191VJLH7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwHmgO6EtJrbF1ZTHr-ZzMOMtWestNnZs',
    appId: '1:554206459812:android:b37d402edc2ce19128f331',
    messagingSenderId: '554206459812',
    projectId: 'king-of-sleeping',
    storageBucket: 'king-of-sleeping.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ1c6jtxkvdRI9dUjc2wVy3I6zp_SOYXk',
    appId: '1:554206459812:ios:5cef8d230bc1199828f331',
    messagingSenderId: '554206459812',
    projectId: 'king-of-sleeping',
    storageBucket: 'king-of-sleeping.firebasestorage.app',
    iosBundleId: 'com.example.sleepingKing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQ1c6jtxkvdRI9dUjc2wVy3I6zp_SOYXk',
    appId: '1:554206459812:ios:5cef8d230bc1199828f331',
    messagingSenderId: '554206459812',
    projectId: 'king-of-sleeping',
    storageBucket: 'king-of-sleeping.firebasestorage.app',
    iosBundleId: 'com.example.sleepingKing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCX0qt1vX0t8aj3seceHxAlnKzkHmT4xB4',
    appId: '1:554206459812:web:e92ac6c5cc0793ca28f331',
    messagingSenderId: '554206459812',
    projectId: 'king-of-sleeping',
    authDomain: 'king-of-sleeping.firebaseapp.com',
    storageBucket: 'king-of-sleeping.firebasestorage.app',
    measurementId: 'G-Y7MKV48D33',
  );
}
