// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRwAKRsm50A4ycJvjneEGtJs2l9uaCGvY',
    appId: '1:1079540447962:web:b65da2774d1019ddff03e3',
    messagingSenderId: '1079540447962',
    projectId: 'king-of-sleepers-c221d',
    authDomain: 'king-of-sleepers-c221d.firebaseapp.com',
    storageBucket: 'king-of-sleepers-c221d.firebasestorage.app',
    measurementId: 'G-DL1BQ8W7P8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq12a2mqBfbBZtssgu340Vh-r5ERnmcRA',
    appId: '1:1079540447962:android:700303a33243ad9aff03e3',
    messagingSenderId: '1079540447962',
    projectId: 'king-of-sleepers-c221d',
    storageBucket: 'king-of-sleepers-c221d.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCP7dlJI-0dz1fOmWGXgIwyBg4faKqGdsU',
    appId: '1:1079540447962:ios:727a26075597a34fff03e3',
    messagingSenderId: '1079540447962',
    projectId: 'king-of-sleepers-c221d',
    storageBucket: 'king-of-sleepers-c221d.firebasestorage.app',
    androidClientId: '1079540447962-efeps1lfm63dka113t4146b71dk0p16h.apps.googleusercontent.com',
    iosClientId: '1079540447962-nltq8uf11fgf751hk2uspnosvpinch8b.apps.googleusercontent.com',
    iosBundleId: 'com.example.sleepingKing',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCP7dlJI-0dz1fOmWGXgIwyBg4faKqGdsU',
    appId: '1:1079540447962:ios:727a26075597a34fff03e3',
    messagingSenderId: '1079540447962',
    projectId: 'king-of-sleepers-c221d',
    storageBucket: 'king-of-sleepers-c221d.firebasestorage.app',
    androidClientId: '1079540447962-efeps1lfm63dka113t4146b71dk0p16h.apps.googleusercontent.com',
    iosClientId: '1079540447962-nltq8uf11fgf751hk2uspnosvpinch8b.apps.googleusercontent.com',
    iosBundleId: 'com.example.sleepingKing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRwAKRsm50A4ycJvjneEGtJs2l9uaCGvY',
    appId: '1:1079540447962:web:04c1fcc7728325a4ff03e3',
    messagingSenderId: '1079540447962',
    projectId: 'king-of-sleepers-c221d',
    authDomain: 'king-of-sleepers-c221d.firebaseapp.com',
    storageBucket: 'king-of-sleepers-c221d.firebasestorage.app',
    measurementId: 'G-29NCC5WTND',
  );
}
